### ISSUE TITLE
Where to find MowgliRoverROS?

### ISSUE THREAD

**Issue by mhhagen** [cloudn1ne/Mowgli#13]
A few days ago you updated the INSTALL.md
Everything's fine with this until one reaches the section where you clone the MowgliRoverROS.
The command "git clone git@github.com:cloudn1ne/MowgliRoverROS.git" results in an error as the repository is not found or accessible.
Could you tell how to fix this?

**Comment by mhhagen** [comment]
@cloudn1ne could you give me a hint? Maybe I'm just blind...

**Comment by cloudn1ne** [comment]
Hi, MowgliRoverROS isnt public (and will be deleted), it was just my experimental repo.

The cleanup + documented repo that you want is https://github.com/cloudn1ne/MowgliRover
