### ISSUE TITLE
change ROS publisher topic from "odom" to "mowgli/odom"

### ISSUE THREAD

**Issue by christophsobel** [cloudn1ne/Mowgli#14]
Mowgli Rover expects topic /mowgli/odom but the stm32 node publishes on topic /odom

In file stm32/ros_usbnode/src/ros/ros_custom/cpp_main.cpp

Line 171:
ros::Publisher pubOdom("odom", &odom_msg);

Should be:
ros::Publisher pubOdom("mowgli/odom", &odom_msg);

**Comment by cloudn1ne** [comment]
you are right, atm its rewritten in the launch file - im still experimenting with EKF and dead reckoning, once that works i will fix this (the tf also needs to be broadcasted again)

**Comment by cloudn1ne** [comment]
uploaded version with TF for odom_dr->base_link_dr that also has the topic changed to /mowgli/odom
